### ISSUE TITLE
Fallback URL

### ISSUE THREAD

**Issue by sabeurthabti** [NET-A-PORTER/mrp-url-generator#1]
Hi, 

When one or more parameter is invalid/undefined can we fall back to the pid version of the url?

`.../products/612938`

**Comment by thearegee** [comment]
I think this should be an option, I'm not a fan of falling back unless we are notified it's 'fallen back'. 
Can mask issues.

**Comment by jamesseanwright** [comment]
Hey dude,

In terms of required, undefined parameters, we could pass a flag to fall back to make the altered behaviour obvious to over developers. What would be an example of an invalid parameter?

Also, would you be able to specify your use case? It'd be good to gauge how the scenario would benefit from such a change.

Given the potentially sensitive nature of the last question, can I make this private and get rid of the `circlecitest` repo?

**Comment by sabeurthabti** [comment]
@jamesseanwright ignore, this request.

Yes you can.

**Comment by jamesseanwright** [comment]
:+1:  Making it private now, cheers :)
